### PR TITLE
Read Me and Model Examples Update.

### PR DESCRIPTION
**Pull request by slvrwar**

### CODE REVIEW

**Comment by slvrwar** [comment]
Hey N,
I merged my read me stuff in and it didn't just merge it into the master like I expected. 

I feel like this shouldn't look like this but I haven't merged changes to the API git before so I don't know for sure. 

I was expecting my pull to go straight to the master since I didn't think we have a develop branch for the API repository. 

Thanks for the feedback.

**Comment by nathanntg** [comment]
Same sort of setup for this repo. I would recommend going through the same release project locally (create a release and complete the release via the Git flow commands and push that to the server, rather than using a PR).

**Comment by slvrwar** [comment]
Ok. So it is safe to just close this PR and then do a release and then do I need to push an update somehow like we do for the installations?

**Comment by nathanntg** [comment]
I think so.

**Comment by slvrwar** [comment]
@nathanntg Hey N, Would you check to be sure I did this correctly? 
I believe I did I followed the normal procedure for pushing a release. Just a little simpler here since there is no fork. 
Thanks for double checking me. I really appreciate it.

**Comment by nathanntg** [comment]
Looks great!

**Pull request closed without merging**
